### ISSUE TITLE
Instruction and Image doesn't match

### ISSUE THREAD

**Issue by winston** [jollygoodcode/rails-carrier#7]
In https://github.com/jollygoodcode/rails-carrier/blob/master/README-WINDOWS.md#adjusting-your-path-environment

The instruction says: `Choose option Use Git and optional Unix tools from the Windows Command Prompt.`

But the image has the `Use Git from BASH` checked which is confusing (if I just follow the image).

**Comment by JuanitoFatas** [comment]
Updated image in https://github.com/jollygoodcode/rails-carrier/commit/4e7398573c28f72d016187235501787bbe7dc8fd.
